version: '3.3'
volumes:
  data:
services:
  mysql-app:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=166BBT*p
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql-app
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
